require("core")
require("plugins.cmp")
require("plugins.lsp")
require("plugins.treesitter")
require("plugins.autopairs")
require("plugins.fzf")
require("plugins.undotree")
require("plugins.trouble")
require("plugins.harpoon")

vim.cmd.colorscheme("gruber-darker")
