require("core")
require("plugins.cmp")
require("plugins.lsp")
require("plugins.treesitter")
require("plugins.autopairs")
require("plugins.harpoon")
require("plugins.telescope")
require("plugins.rose-pine")
require("plugins.zen")
vim.cmd("colorscheme impossible")
