require("core")
require("plugins.cmp")
require("plugins.lsp")
require("plugins.treesitter")
require("plugins.autopairs")
require("plugins.fzf")
require("plugins.undotree")
require("plugins.trouble")
require("plugins.harpoon")

vim.cmd("colorscheme monkeys")

vim.api.nvim_set_hl(0, "Normal", { bg = "NONE" })
vim.api.nvim_set_hl(0, "NormalNC", { bg = "NONE" })
vim.api.nvim_set_hl(0, "SignColumn", { bg = "NONE" })
