local opt = vim.opt
vim.g.mapleader = " "

opt.mouse = "a"
opt.number = true
opt.relativenumber = true
opt.signcolumn = "yes"
opt.termguicolors = true
-- opt.colorcolumn = "80"
opt.syntax = "on"
opt.tabstop = 4
opt.shiftwidth = 4
opt.expandtab = true
opt.hlsearch = false
opt.incsearch = true
opt.smartindent = true
opt.autoindent = true
opt.smartcase = true
opt.ignorecase = true
opt.pumheight = 10
opt.updatetime = 200
opt.timeoutlen = 200
opt.scrolloff = 8
opt.sidescrolloff = 7
opt.swapfile = false
opt.undofile = true
opt.undodir = os.getenv("HOME") .. "/.vim/undodir"
opt.wrap = true
opt.showmode = false
opt.clipboard = 'unnamedplus'
opt.statusline = " %f %h%m%r"

vim.opt.ruler = false
vim.opt.showcmd = false
